# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:iXXaTIITGI9C9wVz27rpg3x895N6hgHZVGb95BaE/dp94ru6IF+olR6C+lC69HrnEIgsekyaN4XP3tDmy8VzI2qeHn/hrBkHKqEZDWjRU2ohTY9v+QpdesBQYtRNEpmzDEhmaM1oXpbdEUfYD3ls9kKjFRLOXlWv8HcuYyGTQd8P2Jwq3QeIyrM9kG9FC3iq+w2wX9WCj2oKRqy7zJ7TjP16sG6UlHYFO1aCqRg=,iv:w+iiWOHKlDIAzP/0bRLRrQGLMiKqew5qXBI9oN3EIGs=,tag:YPwbG1OkM7xxUUFpITQUeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15semdv8gcjnwk8krt0zkhua9k0aa3054drh66dxhz0gs637vmpks0hzgl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QmF3YjdXVE5zQUhjL1NX
            bHhVamdmTHhHQzExQ25ZQUxoNG9oMUZZNW04CnczZDlnV2h2MFpUV2NQWWJTMVND
            Qkdad05vN08wa0VXK3ErWWExWER0RkkKLS0tIGcxTm8wZDVGWGZnejR2dmw0eEEr
            WkNvMzhLVUQ0WTgwNGk2c2pmU3orWWsKg+/1jRsWHBzMGN90cAmtwGDdePBbcjdx
            pekFPcey/93nU5qKpSlDZsm9cCozjCD0lJIrHyx5xoOVAAu1HYrpuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-20T14:28:56Z"
    mac: ENC[AES256_GCM,data:eMn++3DdYiR++2XmYXTxz2Gz70PyQE/l+/CuVY7pQf3lF8Wc9eXrkuomZkb4yfoVg7Lt/drG0dggeFTxBOBz/yPxOHHjT5wxfi+1Vuuqkw5AnXoxby6MmRfBC/cz+pYh2ouaGMPNmazteI08tNaEwto2hEUkrWx9BpfVvw35vg4=,iv:G+HqcD4ZOo2qMzuuhuhkmN7OKWXmphmqPE2wC/MWMxQ=,tag:ALdCgAAcEUsc8L6VuhVlWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
