---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.fairwinds.com/stable
      chart: vpa
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 5m
  values:
    recommender:
      extraArgs:
        pod-recommendation-min-cpu-millicores: 15
        pod-recommendation-min-memory-mb: 100
        prometheus-cadvisor-job-name: kubelet
        pod-namespace-label: namespace
        pod-name-label: pod
        container-namespace-label: namespace
        container-pod-name-label: pod
        container-name-label: container
        prometheus-address: |
          http://thanos-query.monitoring.svc.cluster.local:9090
        storage: prometheus
    updater:
      enabled: false
    admissionController:
      enabled: false
