# yamllint disable
# apiVersion: v1
# kind: Secret
# metadata:
#     name: minio-helm-values
#     namespace: tools
# type: Opaque
# stringData:
#     values.yaml: |
#         accessKey:
#         secretKey:
apiVersion: v1
kind: Secret
metadata:
  name: minio-helm-values
  namespace: tools
type: Opaque
stringData:
  rootUser: ENC[AES256_GCM,data:m6rz4uUBtyqXR9uffScQXf6eoHhbP4lWH3o=,iv:O+0u9ywnMXIhdWNOGS8WfTkMd2asl9onsQXRhLGYRlk=,tag:+XRTW7t6/va9dw7mK2cihA==,type:str]
  rootPassword: ENC[AES256_GCM,data:DK9aHK2hAki4x0KJIgVTM0tHVgPD9FD73b0=,iv:6AJh0q23yDUXa5dUglrGu6GQpIj5fpUkElpW5H/u/h4=,tag:t6x06G8MVNd2/Al4epTAiQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age15semdv8gcjnwk8krt0zkhua9k0aa3054drh66dxhz0gs637vmpks0hzgl8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacU11eXFxcnI3QTI1TExu
        cDJ6ejFFYTlPWE1rS05NQU9PYkhRMFpIS0cwCkc3QmxrMk51Q1ZoeVV4czJXWmNN
        dk1LRnJGZlFvcU92YTFaNjRPRmdWclkKLS0tIGpCd2w3Mkhtdy8wZCtNQUswZnpL
        ZWlTUksyYlZBY1U4dDRKZk5OMlh3ZUUKSljOh4HP0Tef8ywWhQTdtcCKyQ+HByf0
        smNSoar17ptkGOi9SbWnyuYfFHStHP6fOgPkaTrR9G8FaHoDz2Wihg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2021-12-20T14:28:56Z"
  mac: ENC[AES256_GCM,data:De3t3nou7bF1zCHr5lvv4QflFEpD8AY/0iElq31KbMpR7YBmj7qEQRUzHG1yfuf1PUF1jziGQMTxkmmcA23W70TPYUo+e4yNa+DD2EC+5tiHy0aBDDOrYiSllHP/f2aNGqN+G1cPCFfAjFK3RFSFenFZo4IGUWi/U9sXBzrv+QY=,iv:VlBv/+UA5urzLRp7rYhJe5Od423KBhlOR55Wc6Kvvzw=,tag:sy2w5r1PaYk7SXDKpATJgQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
