# yamllint disable
# comm_config.yaml: |
#     communications:
#         discord:
#             enabled: true
#             notiftype: short
#             token:
#             botid:
#             channel:
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:mbkS6HVloMNTjayPE6jald3a7TG2p8OJU00iGeHspOP8/H/mpss0qjymljwPy8NkzYhZHGkQnJatWfOfI/V2FHdd64Y4duzC+lARq73xoeWY7bWLcWbjC1gKRWACAa0obJ7/xcEW3bHKirHlLIpzigL8dTTd7s2SsPR9vg9iEXBHU8ZHm1Z1rLO1bQhYcAp83A==,iv:pXDTTuR6sfv6htDpsrKsgivn5nKPwjTdI7XLcpZRpOM=,tag:l4E14aQRKh05T6bP2Ae4+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15semdv8gcjnwk8krt0zkhua9k0aa3054drh66dxhz0gs637vmpks0hzgl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUSt1eUpnZ0NlaGE4ZDNC
            WStkMmVFZFVPamhoRTA3Wjlpc2pSV0F3U0VrClRZV21XeGc3a3RQTk9lbC9OZ0tn
            RkhEdElET3FJVHJnUmRkWU5IQ0FrbXcKLS0tIGV3VExGVVoybHdOSXI5WFdhd1J5
            Ni9CMEpnL1Ywa2RxL2VaZkxXKytjRTQKpLaPBjOopcC2dXaXm+EaNWo7FpeVp44X
            JXi/Owo/vTexANuwPpwAkY1lOWKhhfyo8u28/OQeyWeH10jctELTCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-20T14:28:56Z"
    mac: ENC[AES256_GCM,data:vy4pnywZmiRJ8C6tGr5epszta2bYs5Zl9cgZh1ur7iEou6DJ1zVCx3WbwvWT5p3k9bLNaDDaVcNMQWOhWbTdOu6PPydU1pHyWlO2do3ehheerQPHIP1eyNxWH3PPXP2LKrQKM9iNUcCGRsCsSlQal00IddUh+QQFKgyqNtanfX4=,iv:dAM6kqRYLt01jOGO1EBTsFUzLAYWL2BuWt1P5xqKWqw=,tag:U8ngmtYZDWsucgVbSY0yBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
